### ISSUE TITLE
Stacktrace displayed in MUnit test that intercepts the exception

### ISSUE THREAD

**Issue by ohuu** [typelevel/munit-cats-effect#117]
tpolecat/skunk#511

I raised this issue over on the skunk repo but thought it might be better raised here instead? Any idea why the stack trace is being displayed?

**Comment by armanbilge** [comment]
Thanks for reporting! My guess is this is something specific to Skunk. I don't think there's any `print`s in the munit-cats-effect codebase. Feel free to re-open if you can reproduce without Skunk.
