### ISSUE TITLE
Experiment with time mocking APIs

### ISSUE THREAD

**Issue by djspiewak** [typelevel/munit-cats-effect#123]
How should tests be structured to best take advantage of this and reflect the capability to users in an idiomatic fashion? Not sure! typelevel/cats-effect#2276 exposes a new `TestControl` runtime which makes it relatively straightforward to test `IO` programs under artificial time control.

**Comment by Daenyth** [comment]
I'm using this so far;
```scala

/** Mixin trait providing assertions using cats-effect-testkit `TestControl` */
trait DeterministicTest extends TestInstances { this: munit.FunSuite =>

  def testTicked(
      name: String
  )(body: Ticker => Any)(implicit loc: Location): Unit =
    test(name)(body(Ticker()))

  // NB assertion methods below modeled after tests in cats-effect
  // https://github.com/typelevel/cats-effect/blob/27307cfe6cd9ea3cb230a8f9be5e16f624a914cd/tests/shared/src/test/scala/cats/effect/Runners.scala

  def assertNonTerminating(
      ioa: IO[Unit]
  )(implicit ticker: Ticker, loc: Location): Unit =
    assertTickTo(ioa)(Outcome.succeeded(None))

  def assertSelfCancel[A](
      ioa: IO[Unit]
  )(implicit ticker: Ticker, loc: Location): Unit =
    assertTickTo(ioa)(Outcome.canceled)

  def assertFailAs(io: IO[Unit])(
      expected: Throwable
  )(implicit ticker: Ticker, loc: Location): Unit =
    assertTickTo(io)(Outcome.Errored(expected))

  def assertTickTo[A: Eq: Show](ioa: IO[A])(
      expected: Outcome[Option, Throwable, A]
  )(implicit ticker: Ticker, loc: Location): Unit = {
    val oc = unsafeRun(ioa)
    assert(oc eqv expected, s"${oc.show} !== ${expected.show}")
  }

}
```

**Comment by djspiewak** [comment]
Any particular reason not to use `TestControl`?

**Comment by Daenyth** [comment]
That is using TestControl, via TestInstances#Ticker

**Comment by djspiewak** [comment]
I think Ticker is using TestContext, not TestControl. I guess I'm thinking as much about the API as the implementation, though. Why have the specialized combinators based on Ticker rather than asserting on TestControl?

**Comment by Daenyth** [comment]
No reason. I copy/pasted the assertion code from the tests in cats-effect

**Comment by armanbilge** [comment]
Based on https://github.com/typelevel/munit-cats-effect/pull/142#issuecomment-926936584 I think we no longer need a special integration with time mocking APIs.
