### ISSUE TITLE
Non release builds published to Maven

### ISSUE THREAD

**Issue by brendanmaguire** [typelevel/munit-cats-effect#131]
This may not be a bug but it seems a little unusual to me. It seems all non PR builds are been published to Maven. I noticed this because I have a giter8 project which attempts to use the latest stable version of `munit-cats-effect-2` and the [search used by giter8](https://search.maven.org/solrsearch/select?q=g:%22org.typelevel%22+AND+a:%22munit-cats-effect-2_2.13%22&rows=10&wt=xml&core=gav) only returns non release builds. This is different behaviour to how munit publishes builds as can be seen from the [search result](https://search.maven.org/solrsearch/select?q=g:%22org.scalameta%22+AND+a:%22munit_2.13%22&rows=10&wt=xml&core=gav).

**Comment by rossabaker** [comment]
It's [this setting](https://github.com/typelevel/munit-cats-effect/blob/aa4db61467d6f9d0be050c1c59d028cca116e7b2/build.sbt#L11).  It's convenient in times of churn, but I don't like how it pollutes Maven Central and affects tooling in ways like you describe.

**Comment by brendanmaguire** [comment]
Ah, thanks for the explanation @rossabaker :slightly_smiling_face:  I guess I'll leave the issue open for now and let the maintainer(s) decide if it's desired behaviour or not.
