### ISSUE TITLE
Integrate with upcoming munit v1

### ISSUE THREAD

**Issue by armanbilge** [typelevel/munit-cats-effect#147]
Opening the issue to kick things off, munit v1 is still in the milestone stage.
https://github.com/scalameta/munit/releases/tag/v1.0.0-M1

The most notable changes (so far) are that it now supports async suite-local `Fixture`s 🎉 . Much gratitude to @danicheg for PRing this 👏

My biggest question is: for how long do we still intend to support both CE2 and CE3? Since we are bumping version numbers anyway, I'd be happy to use this opportunity to dump CE2 and the acrobatics this repo uses to share code between them.

**Comment by armanbilge** [comment]
@mpilquist 6 months later, do you still feel the same?

We will shortly be removing http4s 0.22.x from Steward. Meanwhile, I discovered the other day that fs2 2.5.x CI probably hasn't worked for months.

@valencik had the excellent suggestion to look at download stats. Here they are for the CE2 and CE3 versions, don't be fooled by the colors! :)

The majority of the CE2 users have not updated since 1.0.0, which suggests those projects are not actively maintained. Meanwhile, the majority of the CE3 users are on the latest release.

![chart](https://user-images.githubusercontent.com/3119428/162620882-74dee247-c8f4-43c3-a52b-630ff5ecf858.png)

![chart-1](https://user-images.githubusercontent.com/3119428/162620893-f7fac206-9157-42bb-9ff5-0ed6b0854ec6.png)

**Comment by mpilquist** [comment]
No strong opinions here.

**Comment by otto-dev** [comment]
FYI https://scalameta.org/munit/docs/fixtures.html#asynchronous-fixtures-with-custom-effect-type

**Comment by armanbilge** [comment]
Another nail in the coffin.
- https://github.com/typelevel/cats-effect/issues/2988
