### ISSUE TITLE
scalafmt is not enforced in CI

### ISSUE THREAD

**Issue by larsrh** [typelevel/munit-cats-effect#15]
```
java.io.IOException: Supplied file /home/runner/work/munit-cats-effect/munit-cats-effect/target/sonatype-staging/0.4-dca45a0-SNAPSHOT is a not an existing directory!
```

**Comment by mpilquist** [comment]
That happens when something in the build modifies source files — e.g. missing copyright headers or scalafmt

**Comment by tpolecat** [comment]
It can be helpful to have the build do `git status` (or `git diff`) before and after running sbt so you can diagnose this when it happens. Yesterday the doobie build failed because I had an sbt runner in the root directory that was being overwritten.

**Comment by larsrh** [comment]
Right, but I have no idea how to debug this. I don't even see a relevant change in the commit log.

**Comment by larsrh** [comment]
OK, I found the issue. scalafmt is not enforced. Since the GitHub Actions is generated by @djspiewak, maybe he can take a look why it doesn't work.

**Comment by djspiewak** [comment]
@larsrh You probably want something a bit like this: https://github.com/typelevel/cats-effect/blob/series/2.x/build.sbt#L59-L62 Alternatively, you could use `ThisBuild / githubWorkflowBuildPreamble += WorkflowStep.Sbt(List("scalafmtCheckAll"))`
