### ISSUE TITLE
Add a fixture which provides a cats.effect.std.Dispatcher

### ISSUE THREAD

**Issue by mpilquist** [typelevel/munit-cats-effect#29]
Not sure if we need this or not. We can currently do this:

```scala
val dispatcher = CatsEffectFixture.fromResource(Dispatcher[IO])

dispatcher.test("foo") { dispatcher => ... }
```

We could instead instantiate a dispatcher in every `CatsEffectSuite` and setup/tear down in `beforeAll`/`afterAll`. Thoughts?

**Comment by milanvdm** [comment]
Is this something you need to add to each of your Specs otherwise? If so, I would add it as it would take away some boilerplate.

**Comment by mpilquist** [comment]
No, it's pretty uncommon to need a dispatcher in tests. I added an example to the README of showing how to use resource based fixtures and I used `Dispatcher` as the example resource. Closing this one.
