### ISSUE TITLE
Release version doesn't match with artifact version

### ISSUE THREAD

**Issue by marcraminv** [typelevel/munit-cats-effect#35]
Hey 🙂👋!

I was trying to play a bit with the library and I had the following issue

## Context

**Scala Version:** 2.13
**Sbt    Version:** 1.4.1
**Munit Version:** 0.7.14

## Expectation

If I use the last [github tag release](https://github.com/typelevel/munit-cats-effect/releases/tag/v0.3.0) to set the the library dependency, it will be downloaded correctly.

## Actual Behaviour

I checked the release tags, and I used the last one to use the library:

```scala
 libraryDependencies += "org.typelevel" %% "munit-cats-effect-2" % "0.3.0" % "test"
```

But an error appears:
```
2020.10.25 20:35:04 INFO  [error] sbt.librarymanagement.ResolveException: Error downloading org.typelevel:munit-cats-effect-2_2.13:0.3.0
2020.10.25 20:35:04 INFO  [error]   Not found
2020.10.25 20:35:04 INFO  [error]   Not found
2020.10.25 20:35:04 INFO  [error]   not found: /Users/marc/.ivy2/local/org.typelevel/munit-cats-effect-2_2.13/0.3.0/ivys/ivy.xml
2020.10.25 20:35:04 INFO  [error]   not found: https://repo1.maven.org/maven2/org/typelevel/munit-cats-effect-2_2.13/0.3.0/munit-cats-effect-2_2.13-0.3.0.pom
```

I checked the artifact repository and I found theses versions 

<img width="673" alt="image" src="https://user-images.githubusercontent.com/13021787/97116903-b0e26d00-1700-11eb-86ca-761401d7dd28.png">

I used the version `"0.4-5f8036d"`, and it works

**Comment by mpilquist** [comment]
I just released 0.4.0 and updated the README.
